// Static data contract v1 (SDD §10.2): the public read API, generated by
// `plm build` into /data/v1/. A persisted, public shape: changes stay
// backward-compatible; breaking changes ship as /data/v2/ alongside v1.
import { z } from "zod";

const Sha256 = z.string().regex(/^sha256:[0-9a-f]{64}$/);

export const DataRights = z.strictObject({
  status: z.enum(["PUBLIC_DOMAIN", "CC_BY", "CC_BY_SA", "PERMISSION_GRANTED"]),
  license: z.string().optional(),
  attribution: z.string(),
});

export const DataIndex = z.strictObject({
  version: z.literal(1),
  release: z.string(),
  works: z.array(
    z.strictObject({
      id: z.string(),
      title: z.string(),
      authors: z.array(z.string()),
      year: z.number().int(),
      translation: z.strictObject({ translator: z.string(), year: z.number().int() }).optional(),
      rights: DataRights,
      documents: z.array(
        z.strictObject({
          id: z.string(),
          slug: z.string(),
          title: z.string(),
          /** Public reader path, e.g. /archive/marx/works/1848/communist-manifesto/ch01.htm */
          path: z.string(),
          /** Location of the document JSON, relative to /data/v1/. */
          data: z.string(),
          passages: z.number().int(),
          /** Passages covered by a rendering, per rendering file (e.g. "en-plain"). */
          covered: z.record(z.string(), z.number().int()),
        }),
      ),
    }),
  ),
  collections: z.array(
    z.strictObject({
      kind: z.enum(["collection", "reading_path"]),
      id: z.string(),
      title: z.string(),
      description: z.string().optional(),
      rationale: z.string().optional(),
      items: z.array(z.string()),
    }),
  ),
  terms: z.array(z.strictObject({ term: z.string(), data: z.string() })),
});
export type DataIndex = z.infer<typeof DataIndex>;

export const DataPassage = z.strictObject({
  id: z.string(),
  type: z.string(),
  level: z.number().int().optional(),
  label: z.string().optional(),
  /** Layout markup (docs/architecture/layout-markup.md). */
  text: z.string(),
  annotations: z.array(
    z.strictObject({ term: z.string(), match: z.string(), occurrence: z.number().int() }),
  ),
});

export const DataRendering = z.strictObject({
  covers: z.array(z.string()).min(1),
  revision: z.number().int(),
  ai_assisted: z.boolean(),
  /** The source changed since this rendering was written; shown with a warning. */
  stale: z.boolean(),
  /** Layout markup with term tokens, for clients that apply reader preferences. */
  text_raw: z.string(),
  /** Layout markup with tokens resolved to the default wording. */
  text: z.string(),
});

export const DataDocument = z.strictObject({
  version: z.literal(1),
  id: z.string(),
  work_id: z.string(),
  title: z.string(),
  path: z.string(),
  source: z.strictObject({
    provider: z.string(),
    url: z.string(),
    retrieved_at: z.string(),
    via: z.string().optional(),
    attribution: z.string(),
  }),
  passages: z.array(DataPassage),
  /** Keyed by rendering file name without .yml, e.g. "en-plain". */
  renderings: z.record(z.string(), z.array(DataRendering)),
  explanations: z.array(
    z.strictObject({
      id: z.string(),
      kind: z.string(),
      targets: z.array(z.string()),
      text: z.string(),
      sources: z.array(z.record(z.string(), z.union([z.string(), z.number()]))),
      ai_assisted: z.boolean(),
    }),
  ),
});
export type DataDocument = z.infer<typeof DataDocument>;

export const DataTerm = z.strictObject({
  version: z.literal(1),
  term: z.string(),
  aliases: z.array(z.string()),
  original: z.record(z.string(), z.string()),
  definition: z.strictObject({
    short: z.string(),
    long: z.string().optional(),
    sources: z.array(z.record(z.string(), z.union([z.string(), z.number()]))),
  }),
  /** Added in v1 for task 022 (optional, so older readers are unaffected). */
  example: z
    .strictObject({ text: z.string(), passage: z.string(), title: z.string(), href: z.string() })
    .optional(),
  not_to_confuse: z.string().optional(),
  related: z.array(z.strictObject({ term: z.string(), name: z.string() })).optional(),
  /**
   * Other terms mentioned in the card's text (task 024): character ranges into
   * definition.short, not_to_confuse or definition.long, first mention only.
   */
  links: z
    .array(
      z.strictObject({
        field: z.enum(["short", "not_to_confuse", "long"]),
        start: z.number().int(),
        end: z.number().int(),
        term: z.string(),
      }),
    )
    .optional(),
  default: z.string(),
  scoped_defaults: z.array(z.strictObject({ scope: z.string(), rendering: z.string() })),
  renderings: z.array(
    z.strictObject({
      key: z.string(),
      forms: z.record(z.string(), z.string()),
      reason: z.string(),
      limitation: z.string().optional(),
      /** Published tokens showing this rendering by default: community usage, not correctness. */
      usage: z.number().int(),
    }),
  ),
});
export type DataTerm = z.infer<typeof DataTerm>;

export const DataManifest = z.strictObject({
  version: z.literal(1),
  release: z.string(),
  content_commit: z.string(),
  schema_versions: z.strictObject({ content: z.number().int(), data: z.literal(1) }),
  counts: z.strictObject({
    works: z.number().int(),
    documents: z.number().int(),
    passages: z.number().int(),
    renderings: z.number().int(),
    terms: z.number().int(),
  }),
  /** sha256 of every other file in /data/v1/, by relative path. */
  files: z.record(z.string(), Sha256),
});
export type DataManifest = z.infer<typeof DataManifest>;

/**
 * search.json: compact plain-text entries for client-side search, labelled by
 * layer so results can say where a match is (SDD §10.3). Added to v1 as a new
 * file, so existing clients are unaffected.
 */
export const DataSearch = z.strictObject({
  version: z.literal(1),
  release: z.string(),
  documents: z.array(z.strictObject({ path: z.string(), title: z.string(), work: z.string() })),
  entries: z.array(
    z.strictObject({
      /** Index into documents; -1 for vocabulary entries. */
      d: z.number().int(),
      /** Passage id (or term slug for vocabulary). */
      p: z.string(),
      /** Layer: o = original, p = plain English, e = explanation, v = vocabulary. */
      l: z.enum(["o", "p", "e", "v"]),
      t: z.string(),
    }),
  ),
});
export type DataSearch = z.infer<typeof DataSearch>;
